title: Virtual Router Architecture {
  shape: text
  near: top-center
  style: {
    font-size: 75
  }
}

direction: right
classes: {
  core_router: {
    shape: image
    icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FNetworking%2FCloud%20Router.svg
    style: {
      shadow: true
    }
  }
  core_router_A: {
    shape: image
    icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FNetworking%2FCloud%20Router.svg
    style: {
      shadow: true
      font-color: blue
    }
  }
  core_router_B: {
    shape: image
    icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FNetworking%2FCloud%20Router.svg
    style: {
      shadow: true
      font-color: red
    }
  }

  sdwan: {
    shape: image
    icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FNetworking%2FCloud%20Firewall%20Rules.svg
  }

  switch: {
    icon: https://icons.terrastruct.com/azure%2FNetworking%20Service%20Color%2FLocal%20Network%20Gateways.svg
  }
  server: {
    icon: https://icons.terrastruct.com/essentials%2F112-server.svg
  }
  FTM: {
    icon: https://icons.terrastruct.com/essentials%2F112-server.svg
  }
  virtual_connection: {
    style: {
      stroke-dash: 3
      stroke: deepskyblue
      font-color: deepskyblue
      bold: true
    }
  }
  virtual_connection_core: {
    style: {
      stroke-dash: 3
      stroke: green
      font-color: green
      bold: true
    }
  }
}

PRX01: {
  class: server
  DEV-VA5-PPE1: {
    label: DEV-VA5-PPE1 (WSI - A - 1)
    class: core_router_A
    tooltip: MGMT IP: 172.16.23.213
  }
  DEV-VA5-PPE2: {
    label: DEV-VA5-PPE2 (WSI - A - 2)
    class: core_router_A
    tooltip: MGMT IP: 172.16.23.214
  }
  DEV-VA5-PPE3: {
    label: DEV-VA5-PPE3 (WSI - B - 1)
    class: core_router_B
    tooltip: MGMT IP: 172.16.23.240
  }
  DEV-VA5-PPE4: {
    label: DEV-VA5-PPE4 (WSI - B - 2)
    class: core_router_B
    tooltip: MGMT IP: 172.16.23.241
  }
}

PRX02: {
  class: server
  DEV-VA1-PPE1: {
    label: DEV-VA1-PPE1 (AD - A - 1)
    class: core_router_A
    tooltip: MGMT IP: 172.16.23.205
  }
  DEV-VA1-PPE2: {
    label: DEV-VA1-PPE2 (AD - A - 2)
    class: core_router_A
    tooltip: MGMT IP: 172.16.23.206
  }
  DEV-VA6-PPE1: {
    label: DEV-VA6-PPE1 (ML - A - 1)
    class: core_router_A
    tooltip: MGMT IP: 172.16.23.200
  }
  DEV-VA6-PPE2: {
    label: DEV-VA6-PPE2 (ML - A - 2)
    class: core_router_A
    tooltip: MGMT IP: 172.16.23.201
  }
}

PRX03: {
  class: server
  DEV-VA1-PPE3: {
    label: DEV-VA1-PPE3 (AD - B - 1)
    class: core_router_B
    tooltip: MGMT IP: 172.16.23.230
  }
  DEV-VA1-PPE4: {
    label: DEV-VA1-PPE4 (AD - B - 2)
    class: core_router_B
    tooltip: MGMT IP: 172.16.23.231
  }
  DEV-VA7-PPE1: {
    label: DEV-VA7-PPE1 (BN - A - 1)
    class: core_router_A
    tooltip: MGMT IP: 172.16.23.209
  }
  DEV-VA7-PPE2: {
    label: DEV-VA7-PPE2 (BN - A - 2)
    class: core_router_A
    tooltip: MGMT IP: 172.16.23.210
  }
  DEV-VA7-PPE3: {
    label: DEV-VA7-PPE3 (BN - B - 1)
    class: core_router_B
    tooltip: MGMT IP: 172.16.23.238
  }
  DEV-VA7-PPE4: {
    label: DEV-VA7-PPE4 (BN - B - 2)
    class: core_router_B
    tooltip: MGMT IP: 172.16.23.239
  }
}

PRX04: {
  class: server
  DEV-VA2-PPE1: {
    label: DEV-VA2-PPE1 (SY - A - 2)
    class: core_router_A
    tooltip: MGMT IP: 172.16.23.208
  }
  DEV-VA2-PPE2: {
    label: DEV-VA2-PPE2 (SY - A - 1)
    class: core_router_A
    tooltip: MGMT IP: 172.16.23.207
  }
  DEV-VA8-PPE1: {
    label: DEV-VA8-PPE1 (PER - A - 1)
    class: core_router_A
    tooltip: MGMT IP: 172.16.23.203
  }
  DEV-VA8-PPE2: {
    label: DEV-VA8-PPE2 (PER - A - 2)
    class: core_router_A
    tooltip: MGMT IP: 172.16.23.204
  }
}

PRX05: {
  class: server
  DEV-VA2-PPE3: {
    label: DEV-VA2-PPE3 (SY - B - 2)
    class: core_router_B
    tooltip: MGMT IP: 172.16.23.237
  }
  DEV-VA2-PPE4: {
    label: DEV-VA2-PPE4 (SY - B - 1)
    class: core_router_B
    tooltip: MGMT IP: 172.16.23.236
  }
  DEV-VA2-WANAGG1: {
    class: core_router
    tooltip: MGMT IP: 1.1.1.2
  }
  DEV-VA2-SDWAN1: {
    class: sdwan
    tooltip: MGMT IP: 1.1.1.2
  }
  DEV-VA2-SDWAN2: {
    class: sdwan
    tooltip: MGMT IP: 1.1.1.2
  }
  DEV-VA2-WANEM01
  DEV-VA2-SW01: {
    class: switch
  }
}

PRX07: {
  class: server
  DEV-VA3-PPE1: {
    label: DEV-VA3-PPE1 (HUME - A - 1)
    class: core_router_A
    tooltip: MGMT IP: 172.16.23.211
  }
  DEV-VA3-PPE2: {
    label: DEV-VA3-PPE2 (HUME - A - 2)
    class: core_router_A
    tooltip: MGMT IP: 172.16.23.212
  }
  DEV-VSF2-CE1: {
    class: sdwan
    tooltip: MGMT IP: 1.1.1.2
  }
  DEV-VSF2-CE2: {
    class: sdwan
    tooltip: MGMT IP: 1.1.1.2
  }
  DEV-VSF2-SW01: {
    class: switch
  }
  DEV-VSF2-IPERF01
}

PRX08: {
  class: server
  DEV-VA3-PPE3: {
    label: DEV-VA3-PPE3 (HUME - B - 1)
    class: core_router_B
    tooltip: MGMT IP: 172.16.23.244
  }
  DEV-VA3-PPE4: {
    label: DEV-VA3-PPE4 (HUME - B - 2)
    class: core_router_B
    tooltip: MGMT IP: 172.16.23.245
  }
  DEV-VSF1-CE1: {
    class: sdwan
    tooltip: MGMT IP: 1.1.1.2
  }
  DEV-VSF1-CE2: {
    class: sdwan
    tooltip: MGMT IP: 1.1.1.2
  }
  DEV-VA3-FTM01: {
    class: FTM
  }
  DEV-VA3-WANEM02
  DEV-VA3-SW01: {
    class: switch
  }
}

PRX09: {
  class: server
  DEV-VA4-PPE1: {
    label: DEV-VA4-PPE1 (FYSH - A - 1)
    class: core_router_A
    tooltip: MGMT IP: 172.16.23.215
  }
  DEV-VA4-PPE2: {
    label: DEV-VA4-PPE2 (FYSH - A - 2)
    class: core_router_A
    tooltip: MGMT IP: 172.16.23.216
  }
  DEV-VA8-PPE3: {
    label: DEV-VA8-PPE3 (PER - B - 1)
    class: core_router_B
    tooltip: MGMT IP: 172.16.23.232
  }
  DEV-VA8-PPE4: {
    label: DEV-VA8-PPE4 (PER - B - 2)
    class: core_router_B
    tooltip: MGMT IP: 172.16.23.233
  }
}

PRX10: {
  class: server
  DEV-VA4-PPE3: {
    label: DEV-VA4-PPE3 (FYSH - B - 1)
    class: core_router_B
    tooltip: MGMT IP: 172.16.23.242
  }
  DEV-VA4-PPE4: {
    label: DEV-VA4-PPE4 (FYSH - B - 2)
    class: core_router_B
    tooltip: MGMT IP: 172.16.23.243
  }
  DEV-VA6-PPE3: {
    label: DEV-VA6-PPE3 (ML - B - 1)
    class: core_router_B
    tooltip: MGMT IP: 172.16.23.230
  }
  DEV-VA6-PPE4: {
    label: DEV-VA6-PPE4 (ML - B - 2)
    class: core_router_B
    tooltip: MGMT IP: 172.16.23.231
  }
}

DC-SW01: {
  class: switch
}

DC-SW01 -- PRX01: {
  source-arrowhead.label: Twe1/0/1
  target-arrowhead.label: ens1f0
  label: Trunk
  style.stroke: black
}

DC-SW01 -- PRX02: {
  source-arrowhead.label: Twe1/0/3
  target-arrowhead.label: ens1f0
  label: Trunk
  style.stroke: black
}

DC-SW01 -- PRX03: {
  source-arrowhead.label: Twe1/0/5
  target-arrowhead.label: ens1f0
  label: Trunk
  style.stroke: black
}

DC-SW01 -- PRX04: {
  source-arrowhead.label: Twe1/0/7
  target-arrowhead.label: ens1f0
  label: Trunk
  style.stroke: black
}

DC-SW01 -- PRX05: {
  source-arrowhead.label: Twe1/0/9
  target-arrowhead.label: ens1f0
  label: Trunk
  style.stroke: black
}

DC-SW01 -- PRX07: {
  source-arrowhead.label: Twe1/0/13
  target-arrowhead.label: ens1f0
  label: Trunk
  style.stroke: black
}

DC-SW01 -- PRX08: {
  source-arrowhead.label: Twe1/0/15
  target-arrowhead.label: ens1f0
  label: Trunk
  style.stroke: black
}

DC-SW01 -- PRX09: {
  source-arrowhead.label: Twe1/0/17
  target-arrowhead.label: ens1f0
  label: Trunk
  style.stroke: black
}

DC-SW01 -- PRX10: {
  source-arrowhead.label: Twe1/0/19
  target-arrowhead.label: ens1f0
  label: Trunk
  style.stroke: black
}

# Core to Core links
PRX03.DEV-VA1-PPE3 -- PRX03.DEV-VA1-PPE4: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: G0/0/1
  label: Vl1015
  class: virtual_connection_core
}
PRX02.DEV-VA1-PPE1 -- PRX02.DEV-VA1-PPE2: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: G0/0/1
  label: Vl1006
  class: virtual_connection_core
}
PRX04.DEV-VA8-PPE1 -- PRX04.DEV-VA8-PPE2: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: G0/0/1
  label: Vl1010
  class: virtual_connection_core
}
PRX09.DEV-VA8-PPE3 -- PRX09.DEV-VA8-PPE4: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: G0/0/1
  label: Vl1008
  class: virtual_connection_core
}
PRX04.DEV-VA8-PPE1 -- PRX01.DEV-VA5-PPE2: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: G0/0/0
  label: Vl1011
  class: virtual_connection_core
}
PRX04.DEV-VA8-PPE2 -- PRX02.DEV-VA1-PPE1: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: G0/0/0
  label: Vl1012
  class: virtual_connection_core
}
PRX09.DEV-VA8-PPE3 -- PRX03.DEV-VA1-PPE4: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: G0/0/0
  label: Vl1009
  class: virtual_connection_core
}
PRX09.DEV-VA8-PPE4 -- PRX10.DEV-VA6-PPE3: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: G0/0/0
  label: Vl1036
  class: virtual_connection_core
}

PRX02.DEV-VA6-PPE1 -- PRX02.DEV-VA6-PPE2: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: G0/0/1
  label: Vl1040
  class: virtual_connection_core
}

PRX10.DEV-VA6-PPE3 -- PRX10.DEV-VA6-PPE4: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: G0/0/1
  label: Vl1037
  class: virtual_connection_core
}

PRX02.DEV-VA6-PPE1 -- PRX03.DEV-VA7-PPE1: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: G0/0/0
  label: Vl1007
  class: virtual_connection_core
}
PRX02.DEV-VA6-PPE2 -- PRX04.DEV-VA2-PPE1: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: G0/0/0
  label: Vl1043
  class: virtual_connection_core
}
PRX02.DEV-VA6-PPE2 -- PRX09.DEV-VA4-PPE2: {
  source-arrowhead.label: G0/0/2
  target-arrowhead.label: G0/0/0
  label: Vl1039
  class: virtual_connection_core
}
PRX10.DEV-VA6-PPE3 -- PRX03.DEV-VA7-PPE3: {
  source-arrowhead.label: G0/0/2
  target-arrowhead.label: G0/0/2
  label: Vl1038
  class: virtual_connection_core
}
PRX10.DEV-VA6-PPE4 -- PRX03.DEV-VA1-PPE3: {
  source-arrowhead.label: G0/0/2
  target-arrowhead.label: G0/0/0
  label: Vl1035
  class: virtual_connection_core
}
PRX10.DEV-VA6-PPE4 -- PRX08.DEV-VA3-PPE4: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: G0/0/0
  label: Vl1041
  class: virtual_connection_core
}
PRX02.DEV-VA1-PPE2 -- PRX04.DEV-VA2-PPE1: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: G0/0/2
  label: Vl1014
  class: virtual_connection_core
}

PRX04.DEV-VA2-PPE1 -- PRX04.DEV-VA2-PPE2: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: G0/0/1
  label: Vl1016
  class: virtual_connection_core
}
PRX04.DEV-VA2-PPE2 -- PRX01.DEV-VA5-PPE1: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: G0/0/0
  label: Vl1017
  class: virtual_connection_core
}
PRX05.DEV-VA2-PPE3 -- PRX01.DEV-VA5-PPE3: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: G0/0/0
  label: Vl1019
  class: virtual_connection_core
}
PRX05.DEV-VA2-PPE3 -- PRX10.DEV-VA4-PPE3: {
  source-arrowhead.label: G0/0/2
  target-arrowhead.label: G0/0/0
  label: Vl1018
  class: virtual_connection_core
}
PRX05.DEV-VA2-PPE3 -- PRX05.DEV-VA2-PPE4: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: G0/0/1
  label: Vl1020
  class: virtual_connection_core
}
PRX05.DEV-VA2-PPE4 -- PRX03.DEV-VA7-PPE3: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: G0/0/0
  label: Vl1021
  class: virtual_connection_core
}
PRX03.DEV-VA7-PPE1 -- PRX03.DEV-VA7-PPE2: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: G0/0/1
  label: Vl1024
  class: virtual_connection_core
}
PRX03.DEV-VA7-PPE2 -- PRX07.DEV-VA3-PPE2: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: G0/0/0
  label: Vl1025
  class: virtual_connection_core
}
PRX03.DEV-VA7-PPE2 -- PRX01.DEV-VA5-PPE2: {
  source-arrowhead.label: G0/0/2
  target-arrowhead.label: G0/0/2
  label: Vl1026
  class: virtual_connection_core
}
PRX03.DEV-VA7-PPE3 -- PRX03.DEV-VA7-PPE4: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: G0/0/1
  label: Vl1022
  class: virtual_connection_core
}
PRX03.DEV-VA7-PPE4 -- PRX01.DEV-VA5-PPE4: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: G0/0/0
  label: Vl1023
  class: virtual_connection_core
}
PRX01.DEV-VA5-PPE1 -- PRX01.DEV-VA5-PPE2: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: G0/0/1
  label: Vl1034
  class: virtual_connection_core
}
PRX01.DEV-VA5-PPE3 -- PRX01.DEV-VA5-PPE4: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: G0/0/1
  label: Vl1033
  class: virtual_connection_core
}
PRX09.DEV-VA4-PPE1 -- PRX07.DEV-VA3-PPE1: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: G0/0/0
  label: Vl1030
  class: virtual_connection_core
}
PRX10.DEV-VA4-PPE4 -- PRX08.DEV-VA3-PPE3: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: G0/0/0
  label: Vl1028
  class: virtual_connection_core
}
PRX09.DEV-VA4-PPE1 -- PRX09.DEV-VA4-PPE2: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: G0/0/1
  label: Vl1031
  class: virtual_connection_core
}
PRX10.DEV-VA4-PPE3 -- PRX10.DEV-VA4-PPE4: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: G0/0/1
  label: Vl1032
  class: virtual_connection_core
}
PRX07.DEV-VA3-PPE1 -- PRX07.DEV-VA3-PPE2: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: G0/0/1
  label: Vl1029
  class: virtual_connection_core
}
PRX08.DEV-VA3-PPE3 -- PRX08.DEV-VA3-PPE4: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: G0/0/1
  label: Vl1027
  class: virtual_connection_core
}
# ## SDWAN Testing Connections -- PRX05,07 (VA2, VSF1) ###

PRX05.DEV-VA2-WANAGG1 -- PRX05.DEV-VA2-SW01: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: G0/0/0
  label: Vl1500 - WAN Prov1
  class: virtual_connection
}
PRX05.DEV-VA2-SW01 -- PRX05.DEV-VA2-WANEM01: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: ens5
  label: Vl1501 - WAN Prov1
  class: virtual_connection
}

PRX05.DEV-VA2-SW01 -- PRX05.DEV-VA2-WANEM01: {
  source-arrowhead.label: G0/0/4
  target-arrowhead.label: ens7
  label: Vl1502 - WAN Prov1
  class: virtual_connection
}
PRX05.DEV-VA2-SW01 -- PRX05.DEV-VA2-WANEM01: {
  source-arrowhead.label: G0/0/5
  target-arrowhead.label: ens8
  label: Vl1503 - WAN Prov2
  class: virtual_connection
}

PRX05.DEV-VA2-WANAGG1 -- PRX05.DEV-VA2-SDWAN1: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: Port2
  label: Vl1504
  class: virtual_connection
}

PRX05.DEV-VA2-WANAGG1 -- PRX05.DEV-VA2-SDWAN2: {
  source-arrowhead.label: G0/0/2
  target-arrowhead.label: Port2
  label: Vl1505
  class: virtual_connection
}

PRX05.DEV-VA2-WANAGG1 -- PRX05.DEV-VA2-SW01: {
  source-arrowhead.label: G0/0/3
  target-arrowhead.label: G0/0/2
  label: Vl1506 - WAN Prov2
  class: virtual_connection
}

PRX05.DEV-VA2-SW01 -- PRX05.DEV-VA2-WANEM01: {
  source-arrowhead.label: G0/0/3
  target-arrowhead.label: ens6
  label: Vl1507 - WAN Prov2
  class: virtual_connection
}

PRX05.DEV-VA2-PPE3 -- PRX05.DEV-VA2-SDWAN1: {
  source-arrowhead.label: G0/0/6
  target-arrowhead.label: Port1
  label: Vl1508
  class: virtual_connection
}
PRX05.DEV-VA2-PPE4 -- PRX05.DEV-VA2-SDWAN2: {
  source-arrowhead.label: G0/0/6
  target-arrowhead.label: Port1
  label: Vl1509
  class: virtual_connection
}
PRX07.DEV-VSF2-CE1 -- PRX05.DEV-VA2-WANEM01: {
  source-arrowhead.label: Port1
  target-arrowhead.label: ens3
  label: Vl1510 - WAN Prov1
  class: virtual_connection
}
PRX07.DEV-VSF2-CE2 -- PRX05.DEV-VA2-WANEM01: {
  source-arrowhead.label: Port1
  target-arrowhead.label: ens4
  label: Vl1511 - WAN Prov1
  class: virtual_connection
}
PRX07.DEV-VSF2-CE1 -- PRX05.DEV-VA2-WANEM01: {
  source-arrowhead.label: Port2
  target-arrowhead.label: ens1
  label: Vl1512 - WAN Prov2
  class: virtual_connection
}
PRX07.DEV-VSF2-CE2 -- PRX05.DEV-VA2-WANEM01: {
  source-arrowhead.label: Port2
  target-arrowhead.label: ens2
  label: Vl1513 - WAN Prov2
  class: virtual_connection
}
PRX07.DEV-VSF2-CE1 -- PRX07.DEV-VSF2-CE2: {
  source-arrowhead.label: Port3
  target-arrowhead.label: Port3
  label: Vl1514
  class: virtual_connection
}

PRX07.DEV-VSF2-SW01 -- PRX07.DEV-VSF2-CE1: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: Port4
  label: Vl1516
  class: virtual_connection
}
PRX07.DEV-VSF2-SW01 -- PRX07.DEV-VSF2-CE2: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: Port4
  label: Vl1517
  class: virtual_connection
}

# ## SDWAN Testing Connections -- PRX08 (VA3) ###

PRX08.DEV-VA3-PPE3 -- PRX08.DEV-VA3-WANEM02: {
  source-arrowhead.label: G0/0/6
  target-arrowhead.label: ens1
  label: Vl1500
  class: virtual_connection
}
PRX08.DEV-VA3-PPE4 -- PRX08.DEV-VA3-WANEM02: {
  source-arrowhead.label: G0/0/6
  target-arrowhead.label: ens2
  label: Vl1501
  class: virtual_connection
}
PRX08.DEV-VSF1-CE1 -- PRX08.DEV-VA3-WANEM02: {
  source-arrowhead.label: Port1
  target-arrowhead.label: ens3
  label: Vl1502
  class: virtual_connection
}
PRX08.DEV-VSF1-CE2 -- PRX08.DEV-VA3-WANEM02: {
  source-arrowhead.label: Port1
  target-arrowhead.label: ens4
  label: Vl1503
  class: virtual_connection
}
PRX08.DEV-VA3-SW01 -- PRX08.DEV-VSF1-CE1: {
  source-arrowhead.label: G0/0/0
  target-arrowhead.label: Port4
  label: Vl1511
  class: virtual_connection
}
PRX08.DEV-VA3-SW01 -- PRX08.DEV-VSF1-CE2: {
  source-arrowhead.label: G0/0/1
  target-arrowhead.label: Port4
  label: Vl1512
  class: virtual_connection
}

# ## Test End point Connections ###
PRX07.DEV-VSF2-IPERF01 -- PRX08.DEV-VA3-SW01: {
  source-arrowhead.label: ens2
  target-arrowhead.label: G0/0/8
  label: Vl1513
  class: virtual_connection
}
PRX07.DEV-VSF2-IPERF01 -- PRX05.DEV-VA2-SW01: {
  source-arrowhead.label: ens1
  target-arrowhead.label: G0/0/8
  label: Vl1515
  class: virtual_connection
}
